# Licensed under the Apache-2.0 license

[package]
name = "openprot-hal-nb"
version = "0.1.0"
edition = "2021"
description = "Non-blocking HAL traits for OpenPRoT"
license = "Apache-2.0"

[dependencies]
embedded-hal-nb = "1.0"
nb = "1.0"