# Licensed under the Apache-2.0 license

[package]
name = "crypto-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
ecdsa = []

[dependencies]
zerocopy = { version = "0.8", features = ["derive"] }
