# Licensed under the Apache-2.0 license

[package]
name = "crypto-client"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
path = "src/lib.rs"

[features]
default = []
ecdsa = ["crypto-api/ecdsa"]

[dependencies]
crypto-api = { path = "../api" }
zerocopy = { version = "0.8", features = ["derive"] }
pw_status = { version = "0.1" }

# userspace will be provided by Bazel build
