[book]
authors = ["OpenProt Team"]
language = "en"
multilingual = false
src = "src"
title = "OpenProt Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["src/third_party/mermaid.min.js", "src/third_party/mermaid-init.js"]
additional-css = ["theme/custom.css"]
default-theme = "light"

[output.html.fold]
enable = true
level = 1
